name: test
on:
  # run tests on push to master, but not when other branches are pushed to
  push:
    branches:
      - master

  # run tests for all pull requests
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        # list of jobs to run:
        go:
          - 1.21.x

    name: Go ${{ matrix.go }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check go.mod/go.sum
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false
          version: "2022.1.3"

      - name: Go build
        run: |
          go build ./...

      - name: Go test
        run: |
          go test -cover ./...
